exchange: binance # fetch ticker info from binance. supported exchanges binance, okx, bybit, bitget
instance: binance
symbol:
  - BTCUSDT

Debug: true

database:
  provider: postgresql  # sqlite or postgresql 
  connectionString: "host=localhost port=5432 user=postgres password=saimajj dbname=kline_db sslmode=disable" # for sqlight ./data/kline.db


Aggregator:
  EnableJitter: true
  JitterMaxMillis: 800   # random delay between 0–800ms per goroutine
  EnableBatchStats: true
  PersistRawTicks:
    Enabled: false
    Output: "redis"   # "redis" or "kafka"

Streaming:
  Enabled: false
  Provider: "redis" # or "kafka"
  Redis:
    Address: "localhost:6379"
    Stream: "ticks"
    Password: "your_password"
    DB: 0
  Kafka:
    Brokers:
      - "localhost:9092"
    Topic: "tickdata"
