exchange: bitget
instance: bitget
symbol:
- 10000000AIDOGEUSDT_UMCBL
- 1000BONKUSDT_UMCBL
- 1000CATUSDT_UMCBL
- 1000XECUSDT_UMCBL
- 1MBABYDOGEUSDT_UMCBL
- 1MCHEEMSUSDT_UMCBL
- ACTUSDT_UMCBL
- AGTUSDT_UMCBL
- AINUSDT_UMCBL
- ALPHAUSDT_UMCBL
- ALTUSDT_UMCBL
- AMPUSDT_UMCBL
- ANIMEUSDT_UMCBL
- ANKRUSDT_UMCBL
- ARCUSDT_UMCBL
- ARPAUSDT_UMCBL
- ASRRUSDT_UMCBL
- ASTRUSDT_UMCBL
- ATAUSDT_UMCBL
- ATHUSDT_UMCBL
- AWEUSDT_UMCBL
- B3USDT_UMCBL
- BABYUSDT_UMCBL
- BADGERUSDT_UMCBL
- BANANAS31USDT_UMCBL
- BANKUSDT_UMCBL
- BANUSDT_UMCBL
- BDXNUSDT_UMCBL
- BGSCUSDT_UMCBL
- BIGTIMEUSDT_UMCBL
- BIOUSDT_UMCBL
- BOMBUSDT_UMCBL
- BOMEUSDT_UMCBL
- BRETTUSDT_UMCBL
- BROCCOLIUSDT_UMCBL
- BSWUSDT_UMCBL
- BULLAUSDT_UMCBL
- C98USDT_UMCBL
- CBKUSDT_UMCBL
- CELRUSDT_UMCBL
- CHILLGUYUSDT_UMCBL
- CHZUSDT_UMCBL
- CKBUSDT_UMCBL
- COSUSDT_UMCBL
- COTIUSDT_UMCBL
- CROSSUSDT_UMCBL
- CTCUSDT_UMCBL
- CTSIUSDT_UMCBL
- DEGENUSDT_UMCBL
- DFUSDT_UMCBL
- DMCUSDT_UMCBL
- DOLOUSDT_UMCBL
- DOODUSDT_UMCBL
- ELDEUSDT_UMCBL
- EPTUSDT_UMCBL
- FIOUSDT_UMCBL
- FLMUSDT_UMCBL
- FUNUSDT_UMCBL
- FUSDT_UMCBL
- GALAUSDT_UMCBL
- GIGAUSDT_UMCBL
- GLMUSDT_UMCBL
- GMTUSDT_UMCBL
- GNOUSDT_UMCBL
- GPSUSDT_UMCBL
- GRIFFAINUSDT_UMCBL
- GUNUSDT_UMCBL
- HIPPOUSDT_UMCBL
- HOMEUSDT_UMCBL
- HOUSEUSDT_UMCBL
- HUMAUSDT_UMCBL
- HUSDT_UMCBL
- IDOLUSDT_UMCBL
- IOSTUSDT_UMCBL
- IOTXUSDT_UMCBL
- JASMYUSDT_UMCBL
- JSTUSDT_UMCBL
- KILOUSDT_UMCBL
- KMNOUSDT_UMCBL
- KOMAUSDT_UMCBL
- LOKAUSDT_UMCBL
- MAVUSDT_UMCBL
- MBOXUSDT_UMCBL
- MEMEUSDT_UMCBL
- MEWUSDT_UMCBL
- MILKUSDT_UMCBL
- MUBARAKUSDT_UMCBL
- MYROUSDT_UMCBL
- NAVXUSDT_UMCBL
- NEIROCTOUSDT_UMCBL
- NFPUSDT_UMCBL
- NKNUSDT_UMCBL
- NODEUSDT_UMCBL
- NOTUSDT_UMCBL
- NSUSDT_UMCBL
- OGNUSDT_UMCBL
- OLUSDT_UMCBL
- OMNI1USDT_UMCBL
- ONEUSDT_UMCBL
- OXTUSDT_UMCBL
- PENGUUSDT_UMCBL
- PEOPLEUSDT_UMCBL
- PFVSUSDT_UMCBL
- PIPPINUSDT_UMCBL
- PIUSDT_UMCBL
- PIXELUSDT_UMCBL
- PORT3USDT_UMCBL
- PORTALUSDT_UMCBL
- PUMPBTCUSDT_UMCBL
- PYRUSDT_UMCBL
- QUICKUSDT_UMCBL
- RADUSDT_UMCBL
- RAREUSDT_UMCBL
- RDNTUSDT_UMCBL
- REIUSDT_UMCBL
- REZUSDT_UMCBL
- RONUSDT_UMCBL
- ROSEUSDT_UMCBL
- RSRUSDT_UMCBL
- RVNUSDT_UMCBL
- RWAUSDT_UMCBL
- SHMUSDT_UMCBL
- SIGNUSDT_UMCBL
- SIRENUSDT_UMCBL
- SKATEUSDT_UMCBL
- SkLUSDT_UMCBL
- SKYAIUSDT_UMCBL
- SOLVUSDT_UMCBL
- SOPHUSDT_UMCBL
- SPKUSDT_UMCBL
- SUNUSDT_UMCBL
- SWARMSUSDT_UMCBL
- SWELLUSDT_UMCBL
- SYSUSDT_UMCBL
- TGTUSDT_UMCBL
- TLMUSDT_UMCBL
- TOSHIUSDT_UMCBL
- TRUUSDT_UMCBL
- TUSDT_UMCBL
- TUTUSDT_UMCBL
- USTCUSDT_UMCBL
- VANRYUSDT_UMCBL
- VELODROMEUSDT_UMCBL
- VETUSDT_UMCBL
- VINEUSDT_UMCBL
- VOXELUSDT_UMCBL
- VTHOUSDT_UMCBL
- WAVESUSDT_UMCBL
- WAXPUSDT_UMCBL
- XAIUSDT_UMCBL
- XAUTUSDT_UMCBL
- XCNUSDT_UMCBL
- XIONUSDT_UMCBL
- XVGUSDT_UMCBL
- ZEREBROUSDT_UMCBL
- ZILUSDT_UMCBL
- ZKUSDT_UMCBL
- 10000ELONUSDT_UMCBL
- 10000WHYUSDT_UMCBL
- 1000RATSUSDT_UMCBL
- AGIUSDT_UMCBL
- AIOZUSDT_UMCBL
- AUDIOUSDT_UMCBL
- AVAILUSDT_UMCBL
- BALUSDT_UMCBL
- BEAMUSDT_UMCBL
- BLASTUSDT_UMCBL
- CARVUSDT_UMCBL
- COREUSDT_UMCBL
- CROUSDT_UMCBL
- CUDISUSDT_UMCBL
- DBRUSDT_UMCBL
- DGBUSDT_UMCBL
- DOGUSDT_UMCBL
- DUCKUSDT_UMCBL
- ELXUSDT_UMCBL
- FLOKIUSDT_UMCBL
- FRAGUSDT_UMCBL
- FUELUSDT_UMCBL
- FWOGUSDT_UMCBL
- GODSUSDT_UMCBL
- GORKUSDT_UMCBL
- JUSDT_UMCBL
- LAUNCHCOINUSDT_UMCBL
- LOOKSUSDT_UMCBL
- LUMIAUSDT_UMCBL
- LUNAUSDT_UMCBL
- LUNCUSDT_UMCBL
- MAJORUSDT_UMCBL
- OBTUSDT_UMCBL
- ORBSUSDT_UMCBL
- ORDERUSDT_UMCBL
- PEAQUSDT_UMCBL
- PRCLUSDT_UMCBL
- RFCUSDT_UMCBL
- ROAMUSDT_UMCBL
- RSS3USDT_UMCBL
- SERAPHUSDT_UMCBL
- SHIBUSDT_UMCBL
- SLPUSDT_UMCBL
- SNTUSDT_UMCBL
- SUNDOGUSDT_UMCBL
- SWEATUSDT_UMCBL
- SYNUSDT_UMCBL
- TAIUSDT_UMCBL
- TSTBSCUSDT_UMCBL
- VELOUSDT_UMCBL
- XCHUSDT_UMCBL
- XDCUSDT_UMCBL
- ZBCNUSDT_UMCBL
- ZENTUSDT_UMCBL
- ZORAUSDT_UMCBL
- ZRCUSDT_UMCBL
blacklisted_symbols:
- BOMBUSDT_UMCBL
- DEGENUSDT_UMCBL
- ELDEUSDT_UMCBL
- KILOUSDT_UMCBL
- LOKAUSDT_UMCBL
- PFVSUSDT_UMCBL
- PUMPBTCUSDT_UMCBL
- SOPHUSDT_UMCBL
- TGTUSDT_UMCBL
- VELODROMEUSDT_UMCBL
Aggregator:
  EnableJitter: true
  JitterMaxMillis: 800
  EnableBatchStats: true
  PersistRawTicks:
    Enabled: false
    Output: redis
Streaming:
  Enabled: false
  Provider: redis
  Redis:
    Address: localhost:6379
    Stream: ticks
    Password: your_password
    DB: 0
  Kafka:
    Brokers:
    - localhost:9092
    Topic: tickdata
Debug: false
database:
  provider: postgresql
  connectionString: "" # 🔐 Leave empty. Set DB config via env vars:
                       # DB_HOST=localhost
                       # DB_PORT=5432
                       # DB_USER=postgres
                       # DB_PASSWORD=yourpassword
                       # DB_NAME=kline_db
RefreshSeconds : 5 # 5 second interval (min 4)