exchange: binance

apiKey: "your_api_key"
secretKey: "your_secret_key"
passPhrase: "your_passphrase"

symbol:
  - BTCUSDT
  - ETHUSDT
  - SOLUSDT
  - XRPUSDT

database:
  provider: sqlite
  connectionString: "./data/kline.db"

Aggregator:
  EnableJitter: true
  JitterMaxMillis: 800   # random delay between 0–800ms per goroutine
  EnableBatchStats: true
  PersistRawTicks:
    Enabled: false
    Output: "redis"   # "redis" or "kafka"

Streaming:
  Enabled: true
  Provider: "redis" # or "kafka"
  Redis:
    Address: "localhost:6379"
    Stream: "ticks"
  Kafka:
    Brokers:
      - "localhost:9092"
    Topic: "tickdata"
